### ISSUE TITLE
Colours on the live deployed site differ from those in local development

### ISSUE THREAD

**Issue by pacharanero** [rcpch/epilepsy12-documentation#17]
I can't explain why but the colours in use are different depending on whether you are serving from localhost or viewing a deployed site

If I run mkdocs serve then visit http://localhost:8001/ the colours reflect RCPCH brand guidance

However at the live deployments they are standard Material for MkDocs blues.
https://epilepsy12docs.rcpch.tech/ (live branch)
https://witty-bush-03ee83f03-prerelease.westeurope.1.azurestaticapps.net/ (prerelease)

There are no errors (eg 404s for CSS resources) in the console.

Anyone any thoughts? @anchit-chandran @eatyourpeas

**Comment by eatyourpeas** [comment]
***@***.***

From: Marcus Baw ***@***.***>
Date: Friday, 12 May 2023 at 17:34
To: rcpch/epilepsy12-documentation ***@***.***>
Cc: Simon Chapman ***@***.***>, Mention ***@***.***>
Subject: [rcpch/epilepsy12-documentation] Colours on the live deployed site differ from those in local development (Issue #17)

I can't explain why but the colours in use are different depending on whether you are serving from localhost or viewing a deployed site

If I run mkdocs serve then visit http://localhost:8001/ the colours reflect RCPCH brand guidance

However at the live deployments they are standard Material for MkDocs blues.
https://epilepsy12docs.rcpch.tech/ (live branch)
https://witty-bush-03ee83f03-prerelease.westeurope.1.azurestaticapps.net/ (prerelease)

There are no errors (eg 404s for CSS resources) in the console.

Anyone any thoughts? @anchit-chandran<https://github.com/anchit-chandran> @eatyourpeas<https://github.com/eatyourpeas>

**Comment by pacharanero** [comment]
There is no content in your comment via email.... :smile:

**Comment by eatyourpeas** [comment]
![image](https://github.com/rcpch/epilepsy12-documentation/assets/1058647/12c9f2fe-b290-494e-ac9a-77c283556493)

**Comment by pacharanero** [comment]
However... the documentation sites are all Material for MkDocs, not Django.... so no staticfiles configs. Will have to investigate further what is being missed in the build step.
